export const FAKE_POPULARS = [
  {
    adult: false,
    backdrop_path: "/qWQSnedj0LCUjWNp9fLcMtfgadp.jpg",
    genre_ids: [28, 12, 878],
    id: 667538,
    original_language: "en",
    original_title: "Transformers: Rise of the Beasts",
    overview:
      "When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals. With the fate of humanity hanging in the balance, humans Noah and Elena will do whatever it takes to help the Transformers as they engage in the ultimate battle to save Earth.",
    popularity: 10053.202,
    poster_path: "/gPbM0MK8CP8A174rmUwGsADNYKD.jpg",
    release_date: "2023-06-06",
    title: "Transformers: Rise of the Beasts",
    video: false,
    vote_average: 7.3,
    vote_count: 1383,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/iEFuHjqrE059SmflBva1JzDJutE.jpg",
    id: 496450,
    title: "Miraculous: Ladybug & Cat Noir, The Movie",
    original_language: "fr",
    original_title: "Miraculous - le film",
    overview:
      "A life of an ordinary Parisian teenager Marinette goes superhuman when she becomes Ladybug. Bestowed with magical powers of creation, Ladybug must unite with her opposite, Cat Noir, to save Paris as a new villain unleashes chaos unto the city.",
    poster_path: "/dQNJ8SdCMn3zWwHzzQD2xrphR1X.jpg",
    media_type: "movie",
    genre_ids: [16, 10751, 28, 14, 10749],
    popularity: 169.863,
    release_date: "2023-07-05",
    video: false,
    vote_average: 7.7,
    vote_count: 25,
  },
  {
    adult: false,
    backdrop_path: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    id: 569094,
    title: "Spider-Man: Across the Spider-Verse",
    original_language: "en",
    original_title: "Spider-Man: Across the Spider-Verse",
    overview:
      "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
    poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    media_type: "movie",
    genre_ids: [28, 12, 16, 878],
    popularity: 1238.206,
    release_date: "2023-05-31",
    video: false,
    vote_average: 8.514,
    vote_count: 2347,
  },
  {
    adult: false,
    backdrop_path: "/xGIeqQunSj5dxGZVKzNNr9W4vps.jpg",
    id: 298618,
    title: "The Flash",
    original_language: "en",
    original_title: "The Flash",
    overview:
      "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
    poster_path: "/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg",
    media_type: "movie",
    genre_ids: [28, 12, 878],
    popularity: 1513.344,
    release_date: "2023-06-13",
    video: false,
    vote_average: 6.934,
    vote_count: 1106,
  },
  {
    adult: false,
    backdrop_path: "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
    id: 385687,
    title: "Fast X",
    original_language: "en",
    original_title: "Fast X",
    overview:
      "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    poster_path: "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
    media_type: "movie",
    genre_ids: [28, 80, 53],
    popularity: 2053.681,
    release_date: "2023-05-17",
    video: false,
    vote_average: 7.333,
    vote_count: 2784,
  },
  {
    adult: false,
    backdrop_path: "/6Zfxsiep7L3KPjOmhGr1nwAlzld.jpg",
    id: 877100,
    title: "Lewis Hamilton - Le virtuose",
    original_language: "fr",
    original_title: "Lewis Hamilton - Le virtuose",
    overview: "",
    poster_path: "/iQWpg9ZDLbmJktyhQnPd1StvmsE.jpg",
    media_type: "movie",
    genre_ids: [99],
    popularity: 1.214,
    release_date: "2015-10-26",
    video: false,
    vote_average: 10,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: "/7tRjWRiXUXwKUgDYHnRVPKvdK60.jpg",
    id: 598331,
    title: "Rumble",
    original_language: "en",
    original_title: "Rumble",
    overview:
      "In a world where monster wrestling is a global sport and monsters are superstar athletes, teenage Winnie seeks to follow in her father’s footsteps by coaching a loveable underdog monster into a champion.",
    poster_path: "/fL7rh6Mzx87MbVl2aI4sYtxfhO5.jpg",
    media_type: "movie",
    genre_ids: [16, 10751],
    popularity: 25.681,
    release_date: "2021-12-15",
    video: false,
    vote_average: 6.875,
    vote_count: 447,
  },
  {
    adult: false,
    backdrop_path: "/lkCDvf3QjXpAycm896oH1LRTK5X.jpg",
    id: 462883,
    title: "Woody Woodpecker",
    original_language: "en",
    original_title: "Woody Woodpecker",
    overview:
      "Woody Woodpecker enters a turf war with a big city lawyer wanting to tear down his home in an effort to build a house to flip.",
    poster_path: "/vFGUsJTa8z0OfDTbjdyppAireeB.jpg",
    media_type: "movie",
    genre_ids: [35, 10751, 16],
    popularity: 35.074,
    release_date: "2017-10-05",
    video: false,
    vote_average: 6.683,
    vote_count: 631,
  },
  {
    adult: false,
    backdrop_path: "/rsVf3VqUk7kOnQgfIr5rmSYhmFc.jpg",
    id: 979296,
    title: "Sonic Drone Home",
    original_language: "en",
    original_title: "Sonic Drone Home",
    overview:
      "Sonic, Tails, and Knuckles encounter an abandoned Badnik drone which upgraded itself using parts from a junkyard, with the intention of conquering the world.",
    poster_path: "/ifc2YN7eZeHKwaoiT0Xn8LiJCFb.jpg",
    media_type: "movie",
    genre_ids: [16, 28, 10751, 35, 878],
    popularity: 23.428,
    release_date: "2022-05-24",
    video: false,
    vote_average: 7.2,
    vote_count: 34,
  },
  {
    adult: false,
    backdrop_path: "/8FhKnPpql374qyyHAkZDld93IUw.jpg",
    id: 536437,
    title: "Hypnotic",
    original_language: "en",
    original_title: "Hypnotic",
    overview:
      "A detective becomes entangled in a mystery involving his missing daughter and a secret government program while investigating a string of reality-bending crimes.",
    poster_path: "/3IhGkkalwXguTlceGSl8XUJZOVI.jpg",
    media_type: "movie",
    genre_ids: [9648, 53, 878],
    popularity: 442.359,
    release_date: "2023-05-11",
    video: false,
    vote_average: 6.379,
    vote_count: 319,
  },
  {
    adult: false,
    backdrop_path: "/mK0a3t62lM8ho3mmvBWf6NxdWvw.jpg",
    id: 532408,
    title: "The Boogeyman",
    original_language: "en",
    original_title: "The Boogeyman",
    overview:
      "Still reeling from the tragic death of their mother, a teenage girl and her younger sister find themselves plagued by a sadistic presence in their house and struggle to get their grieving father to pay attention before it’s too late.",
    poster_path: "/pYwZdnXVnVxAr7dx4MEK7tTK9gI.jpg",
    media_type: "movie",
    genre_ids: [27, 9648, 14],
    popularity: 63.43,
    release_date: "2023-05-31",
    video: false,
    vote_average: 6.3,
    vote_count: 119,
  },
];
